Repository YAPP-Github/21st-ALL-Rounder-Team-1-iOS, pull requests merged in 2022-12, with the labels that each got.

#26 Feature/#24 storeCollectinViewCell 및 HomeVC 추가
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Domain/Store.swift
  RefillStation/RefillStation/Domain/StoreInfo.swift
  RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
Labels: 🪄 style, 💻 클로이

#28 Feature/#27 HomeVC에 SearchBar 추가 및 서비스 지역 아닐 시 헤더 추가
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Presentation/HomeScene/View/RegionRequestHeaderView.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
  RefillStation/RefillStation/Resources/images.xcassets/regionImage.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/regionImage.imageset/IMG_7165.png
  RefillStation/RefillStation/Resources/images.xcassets/regionImage.imageset/IMG_7165@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/regionImage.imageset/IMG_7165@3x.png
Labels: ✨ feat, 🪄 style, 💻 클로이

#30 Feature/#29 RequestRegionVC 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewController/RequestRegionViewController.swift
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewModel/RequestRegionViewModel.swift
Labels: ✨ feat, 🪄 style, 💻 클로이

#33 Feature/#31
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/AppDelegate.swift
  RefillStation/RefillStation/Presentation/HomeScene/View/RegionRequestHeaderView.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductListViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailTabViewController.swift
Labels: 🪄 style, 💻 조지, 🧹 chore

#40 [Feat] #39 dynamic cell height 적용 위한 로직 추가
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreReview/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreReview/StoreReviewSection.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreReview/StoreReviewViewController.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
Labels: ✨ feat, 💻 조지

#42 [Feat] #41 더보기 버튼 추가 및 눌렀을때의 로직 제작
  RefillStation/RefillStation.xcodeproj/xcuserdata/neph.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreReview/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreReview/StoreReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreReview/ViewModel/DetailReviewViewModel.swift
Labels: ✨ feat, 💻 조지

#45 [Fix] #44 HomeSceneCoordinator의 메소드명이 프로토콜 준수하도록 변경
  RefillStation/RefillStation/Application/Coordinator/HomeSceneCoordinator.swift
Labels: 🚨 bug, 💻 클로이

#49 Refactor/#46 StoreDetailVC 제작
  RefillStation/.swiftlint.yml
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation.xcodeproj/xcuserdata/neph.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  RefillStation/RefillStation/Application/AppDelegate.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ProductList/ProductCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ProductList/ProductListHeaderCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ProductList/ProductListViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ProductList/ProductTableView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ProductList/ProductTableViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/Review/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/Review/DetailReviewCountCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/Review/FirstReviewRequestCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/Review/MoveToWriteReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/Review/VotedCountLabelCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/Review/VotedTagCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreDetailInfo/StoreDetailInfoStackView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreDetailInfo/StoreDetailInfoView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreDetailTab/StoreDetailTabViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreReview/StoreReviewSection.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreReview/StoreReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/StoreReview/ViewModel/DetailReviewViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/TabBarHeader/StoreDetailHeaderView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/TabViewDelegate.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/DetailReviewViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/ProductListViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailInfoViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewMockData.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/VotedTagViewModel.swift
Labels: 🔧 refactor, 💻 조지

#48 Feature/#47
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  RefillStation/RefillStation/Common/Cancellable.swift
  RefillStation/RefillStation/Data/Repositories/DefaultHomeRepository.swift
  RefillStation/RefillStation/Data/Repositories/HomeRepository.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/HomeRepository.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/HomeRepositoryInterface.swift
  RefillStation/RefillStation/Domain/UseCases/FetchStoreListUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/SearchStoreListUseCase.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
Labels: 💻 클로이, 🧹 chore

#51 Feature/#50 ProductList의 Domain Layer 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/Coordinator/Coordinator.swift
  RefillStation/RefillStation/Application/Coordinator/HomeSceneCoordinator.swift
  RefillStation/RefillStation/Application/Coordinator/OnboardingSceneCoordinatorDelegate.swift
  RefillStation/RefillStation/Application/DIContainer/StoreDetailDIContainer.swift
  RefillStation/RefillStation/Data/Repositories/DefaultProductListRepository.swift
  RefillStation/RefillStation/Data/Repositories/ProductListRepository.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/ProductListRepository.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/ProductListRepositoryInterface.swift
  RefillStation/RefillStation/Domain/UseCases/FetchProductListUseCase.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/Flow/StoreDetailSceneCoordinator.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductListHeaderCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCountCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/FirstReviewRequestCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/MoveToWriteReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/VotedCountLabelCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/VotedTagCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfo/StoreDetailInfoStackView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfo/StoreDetailInfoView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/TabBarHeader/StoreDetailHeaderView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/ProductListViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: ✨ feat, 💻 조지

#55 Feature/#52 RegisterReview Domain + Data(Repository)
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/PersistentStorages/TagResponseStroage/CoreDataStorage/CoreDataTagResponseStorage.swift
  RefillStation/RefillStation/Data/PersistentStorages/TagResponseStroage/TagResponseStorage.swift
  RefillStation/RefillStation/Data/Repositories/DefaultRegisterReviewRepository.swift
  RefillStation/RefillStation/Data/Repositories/RegisterReviewRepository.swift
  RefillStation/RefillStation/Domain/Entities/UserLevelInfo.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/RegisterReviewRepository.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/RegisterReviewRepositoryInterface.swift
  RefillStation/RefillStation/Domain/UseCases/RegisterReviewUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/UploadReviewImageUseCase.swift
Labels: ✨ feat, 💻 클로이

#54 Feature/#53 detail tag collection제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation.xcodeproj/xcuserdata/neph.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  RefillStation/RefillStation/Domain/Entities/DetailReview.swift
  RefillStation/RefillStation/Domain/UseCases/FetchProductListUseCase.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewTagCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/DetailReviewViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewMockData.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: ✨ feat, 💻 조지
