Repository YAPP-Github/21st-ALL-Rounder-Team-1-iOS, pull requests merged in 2022-11, with the labels that each got.

#2 Feature/#1 TagReviewView 틀 제작
  RefillStation/.DS_Store
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation.xcodeproj/project.xcworkspace/xcuserdata/neph.xcuserdatad/UserInterfaceState.xcuserstate
  RefillStation/RefillStation.xcodeproj/xcuserdata/neph.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  RefillStation/RefillStation/Domain/TagReview.swift
  RefillStation/RefillStation/Presentation/TagReviewView.swift
  RefillStation/RefillStation/Presentation/TagReviewViewModel.swift
  RefillStation/RefillStation/Presentation/VotedTagCollectionView.swift
  RefillStation/RefillStation/Presentation/VotedTagCollectionViewCell.swift
Labels: ✨ feat, 💻 조지

#11 Feature/#6
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Domain/StoreInfo.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfoStackView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfoView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: ✨ feat, 🪄 style, 💻 클로이

#13 Feature/#10 StoreReviewViewController 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation.xcodeproj/xcuserdata/neph.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  RefillStation/RefillStation.xcodeproj/xcuserdata/neph.xcuserdatad/xcschemes/xcschememanagement.plist
  RefillStation/RefillStation/Presentation/DetailReviewCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/DetailReviewTableView.swift
  RefillStation/RefillStation/Presentation/MoveToWriteReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreReviewViewController.swift
  RefillStation/RefillStation/Presentation/TagReviewView.swift
  RefillStation/RefillStation/Presentation/VotedCountLabelCell.swift
  RefillStation/RefillStation/Presentation/VotedTagCollectionView.swift
  RefillStation/RefillStation/Presentation/VotedTagCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/VotedTagViewModel.swift
Labels: 🔧 refactor, ✨ feat, 💻 조지

#15 Feature/#12
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Domain/Product.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductTableView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductTableViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: ✨ feat, 🪄 style, 💻 클로이

#19 Feature #12 불필요한 이니셜라이저 삭제
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductTableView.swift
Labels: ✨ feat, 🪄 style, 💻 클로이

#18 Feature/#14 ReviewWritingVC 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation.xcodeproj/xcuserdata/neph.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  RefillStation/RefillStation.xcodeproj/xcuserdata/neph.xcuserdatad/xcschemes/xcschememanagement.plist
  RefillStation/RefillStation/Application/AppDelegate.swift
  RefillStation/RefillStation/Presentation/ReviewSelectingCollectionView.swift
  RefillStation/RefillStation/Presentation/ReviewSelectingView.swift
  RefillStation/RefillStation/Presentation/ReviewSelectingViewModel.swift
  RefillStation/RefillStation/Presentation/ReviewWritingVC/DefaultTagReviewViewModel.swift
  RefillStation/RefillStation/Presentation/ReviewWritingVC/MockData.swift
  RefillStation/RefillStation/Presentation/ReviewWritingVC/ReviewDescriptionCell.swift
  RefillStation/RefillStation/Presentation/ReviewWritingVC/ReviewPhotoDelegate.swift
  RefillStation/RefillStation/Presentation/ReviewWritingVC/ReviewPhotosCell.swift
  RefillStation/RefillStation/Presentation/ReviewWritingVC/ReviewRegisterCell.swift
  RefillStation/RefillStation/Presentation/ReviewWritingVC/ReviewWritingViewController.swift
  RefillStation/RefillStation/Presentation/ReviewWritingVC/Section.swift
  RefillStation/RefillStation/Presentation/ReviewWritingVC/StoreInfoCell.swift
  RefillStation/RefillStation/Presentation/ReviewWritingVC/TagReviewCell.swift
  RefillStation/RefillStation/Presentation/ReviewWritingVC/VoteTitleCell.swift
  RefillStation/RefillStation/Presentation/StoreReviewVC/DetailReviewCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/StoreReviewVC/DetailReviewViewModel.swift
  RefillStation/RefillStation/Presentation/StoreReviewVC/MoveToWriteReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreReviewVC/StoreReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreReviewVC/VotedCountLabelCell.swift
  RefillStation/RefillStation/Presentation/StoreReviewVC/VotedTagCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/StoreReviewVC/VotedTagViewModel.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
Labels: ✨ feat, 💻 조지

#23 Feature/#22 StoreDetailInfoView 디자인 적용
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfoStackView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfoView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: 🪄 style, 💻 클로이
