Repository YAPP-Github/21st-ALL-Rounder-Team-1-iOS, pull requests merged in 2023-01, with the labels that each got.

#59 Chore/#57 MockData 관리 객체, MockRepository 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/MockEntityData.swift
  RefillStation/RefillStation/Data/Repositories/MockRepositories.swift
  RefillStation/RefillStation/Data/Repositories/RequestRegionRepository.swift
  RefillStation/RefillStation/Data/Repositories/StoreReviewRepository.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/RequestRegionRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/StoreReviewRepositoryInterface.swift
  RefillStation/RefillStation/Domain/UseCases/FetchProductListUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/FetchStoreListUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/RegisterReviewUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/SearchStoreListUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/UploadReviewImageUseCase.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewModel/RequestRegionViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/DetailReviewViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/VotedTagViewModel.swift
Labels: 💻 조지, 🧹 chore

#58 Feature/#53 category list scroll view제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  RefillStation/RefillStation.xcodeproj/xcuserdata/neph.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  RefillStation/RefillStation/Domain/Entities/Product.swift
  RefillStation/RefillStation/Domain/Entities/ProductCategory.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCategoriesCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCategoryCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/ProductListViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: ✨ feat, 💻 조지

#61 Feature/#56 RegisterReviewScene 2차 핸드오프 반영
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/MockEntityData.swift
  RefillStation/RefillStation/Presentation/Component/CTAButton.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ReviewPhotoDelegate.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/Section.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/ReviewDescriptionCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/ReviewPhotosCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/StoreInfoCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/TagReviewCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/VoteTitleCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewPopUpViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewModel/DefaultTagReviewViewModel.swift
  RefillStation/RefillStation/Presentation/ReviewWritingScene/ReviewRegisterCell.swift
  RefillStation/RefillStation/Presentation/ReviewWritingScene/ReviewWritingMockData.swift
  RefillStation/RefillStation/Presentation/ReviewWritingScene/TagReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCategoryCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
  RefillStation/RefillStation/Resources/Colors.xcassets/Primary0.colorset/Contents.json
Labels: ✨ feat, 💻 클로이

#66 [Feature/#64] LevelScene + PumpTagView 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Domain/Entities/UserLevelInfo.swift
  RefillStation/RefillStation/Presentation/Component/PumpTagView.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelHeaderView.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewController/UserLevelViewController.swift
Labels: 🪄 style, 💻 클로이

#68 [Feature/#67] 2차 핸드오프 변경사항 반영
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Presentation/Component/PumpLargeTitleNavigationBar.swift
  RefillStation/RefillStation/Presentation/HomeScene/View/RegionRequestHeaderView.swift
  RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
  RefillStation/RefillStation/Resources/Fonts.swift
  RefillStation/RefillStation/Resources/images.xcassets/img_service area.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/img_service area.imageset/img_service area.png
  RefillStation/RefillStation/Resources/images.xcassets/img_service area.imageset/img_service area@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/img_service area.imageset/img_service area@3x.png
  RefillStation/RefillStation/Resources/images.xcassets/regionImage.imageset/IMG_7165.png
  RefillStation/RefillStation/Resources/images.xcassets/regionImage.imageset/IMG_7165@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/regionImage.imageset/IMG_7165@3x.png
Labels: ✨ feat, 💻 클로이

#71 Feature/#70 Onboarding 화면 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingViewModel.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding1.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding1.imageset/img_onboarding1.png
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding1.imageset/img_onboarding1@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding1.imageset/img_onboarding1@3x.png
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding2.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding2.imageset/img_onboarding2.png
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding2.imageset/img_onboarding2@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding2.imageset/img_onboarding2@3x.png
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding3.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding3.imageset/img_onboarding3.png
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding3.imageset/img_onboarding3@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding3.imageset/img_onboarding3@3x.png
Labels: ✨ feat, 💻 조지

#69 Feature/#53 운영정보탭제작 및 StoreDetail 화면 대규모 리팩토링
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/AppDelegate.swift
  RefillStation/RefillStation/Application/DIContainer/StoreDetailDIContainer.swift
  RefillStation/RefillStation/Data/MockEntityData.swift
  RefillStation/RefillStation/Domain/Entities/DetailReview.swift
  RefillStation/RefillStation/Domain/Entities/Product.swift
  RefillStation/RefillStation/Domain/Entities/Store.swift
  RefillStation/RefillStation/Domain/Entities/Tag.swift
  RefillStation/RefillStation/Domain/Entities/TagReview.swift
  RefillStation/RefillStation/Domain/Entities/User.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/StoreInfoCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/OperationInfo/OperationInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/FilteredProductCountCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCategoriesCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailPhotoReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailPhotoReviewViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCountCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewTagCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/FirstReviewRequestCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/MoveToWriteReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/RankView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/VotedCountLabelCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/VotedTagCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfo/StoreDetailInfoStackView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfo/StoreDetailInfoViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/TabBar/StoreDetailTabBarCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/TabBarHeader/StoreDetailHeaderView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailInfoStackViewDelegate.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailSection.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/DetailReviewViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/ProductListViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailInfoViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/VotedTagViewModel.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
  RefillStation/RefillStation/Resources/Fonts.swift
  RefillStation/RefillStation/Resources/images.xcassets/icon_link.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/icon_link.imageset/icon_link.png
  RefillStation/RefillStation/Resources/images.xcassets/icon_link.imageset/icon_link@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/icon_link.imageset/icon_link@3x.png
Labels: 🔧 refactor, ✨ feat, 💻 조지

#86 Feature/#85 KeychainManager, NetworkService 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/DIContainer/HomeDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/MyPageDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/RegisterReviewDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/StoreDetailDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/TabBarDIContainer.swift
  RefillStation/RefillStation/Data/KeychainManager.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
Labels: ✨ feat, 💻 조지

#82 Feature/#73 온보딩 닉네임 설정, 프로필 수정 뷰 제작, CTAButton 타입 추가
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Presentation/Component/CTAButton.swift
  RefillStation/RefillStation/Presentation/Component/PumpPopUpViewController.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewController/EditProfileBottomSheetViewController.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewModel/NicknameViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewPopUpViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewController/RequestRegionViewController.swift
  RefillStation/RefillStation/Resources/images.xcassets/avatar.imageset/Contents.json~HEAD
  RefillStation/RefillStation/Resources/images.xcassets/avatar.imageset/Contents.json~develop
Labels: ✨ feat, 💻 클로이

#92 Feature/#83 StoreDetail Pop Up 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/Coordinator/StoreDetailCoordinator.swift
  RefillStation/RefillStation/Application/DIContainer/StoreDetailDIContainer.swift
  RefillStation/RefillStation/Data/MockEntityData.swift
  RefillStation/RefillStation/Domain/Entities/User.swift
  RefillStation/RefillStation/Presentation/Component/PumpPopUpViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewReportPopUpViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewReportPopUpViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: ✨ feat, 💻 조지

#95 Feature/#94 MockRepository 제작 및 연결
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/DIContainer/HomeDIContainer.swift
  RefillStation/RefillStation/Data/Repositories/HomeRepository.swift
  RefillStation/RefillStation/Data/Repositories/MockRepositories.swift
  RefillStation/RefillStation/Data/Repositories/ProductsRepository.swift
  RefillStation/RefillStation/Data/Repositories/RegisterReviewRepository.swift
  RefillStation/RefillStation/Data/Repositories/RequestRegionRepository.swift
  RefillStation/RefillStation/Data/Repositories/StoreReviewRepository.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/AccountRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/CustomerSatisfactionRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/HomeRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/ProductsRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/RegisterReviewRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/RequestRegionRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/StoreRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/StoreReviewRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/UserInfoRepositoryInterface.swift
  RefillStation/RefillStation/Domain/UseCases/Account/CreateNicknameUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Account/OAuthLoginUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Account/SignOutUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Account/SignUpUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Account/WithdrawUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Common/UploadImageUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/CustomerSatisfaction/CustomerSatisfactionUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/RegisterReview/RegisterReviewUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/FetchProductsUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/FetchStoreReviewsUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/FetchStoresUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/RecommendStoreUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/UserInfo/EditProfileUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/UserInfo/FetchUserInfoUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/UserInfo/FetchUserReviewsUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/UserInfo/ValidNicknameUseCase.swift
Labels: ✨ feat, 💻 조지

#97 [Feature/#91] OnboardingScene TermsPermissionVC, TermsDetailVC 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/Coordinator/OnboardingCoordinator.swift
  RefillStation/RefillStation/Application/DIContainer/OnboardingDIContainer.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsDetailViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsPermissionViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsPermissionViewModel.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
  RefillStation/RefillStation/Resources/TermsLiterals.swift
  RefillStation/RefillStation/Resources/images.xcassets/Checkbox.imageset/Checkbox.png
  RefillStation/RefillStation/Resources/images.xcassets/Checkbox.imageset/Checkbox@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/Checkbox.imageset/Checkbox@3x.png
  RefillStation/RefillStation/Resources/images.xcassets/Checkbox.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/selectedBox.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/selectedBox.imageset/selected=on, box=on.png
  RefillStation/RefillStation/Resources/images.xcassets/selectedBox.imageset/selected=on, box=on@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/selectedBox.imageset/selected=on, box=on@3x.png
  RefillStation/RefillStation/Resources/images.xcassets/unselectedBox.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/unselectedBox.imageset/selected=off, box=on.png
  RefillStation/RefillStation/Resources/images.xcassets/unselectedBox.imageset/selected=off, box=on@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/unselectedBox.imageset/selected=off, box=on@3x.png
Labels: ✨ feat, 💻 클로이

#102 Feature/#91 축약어 및 내비게이션 백버튼 반영 안된 부분 수정
  RefillStation/RefillStation/Application/DIContainer/OnboardingDIContainer.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsDetailViewController.swift
Labels: 💻 클로이, 🧹 chore

#99 Feature/#96 Dummy Data 생성 로직 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/MockEntityData.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCell.swift
Labels: ✨ feat, 💻 조지

#103 Feature/#100 StoreDetail 서버 연결 밑작업
  RefillStation/RefillStation/Common/Cancellable.swift
  RefillStation/RefillStation/Data/MockEntityData.swift
  RefillStation/RefillStation/Domain/Entities/Store.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: ✨ feat, 💻 조지
