Repository YAPP-Github/21st-ALL-Rounder-Team-1-iOS, pull requests merged in 2023-02, with the labels that each got.

#105 Feature/#98 버그 수정 및 리팩토링
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailPhotoReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailSection.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: 🚨 bug, 🔧 refactor, 💻 조지

#106 [Feature/#101] 리뷰 등록 뷰 변경사항 반영
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ReviewPhotoDelegate.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/ReviewDescriptionCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/ReviewPhotosCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/TagReviewCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/VoteTitleCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewModel/DefaultTagReviewViewModel.swift
Labels: ✨ feat, 💻 클로이

#108 Feature/#104 리뷰작성화면 화면이동 및 서버통신 로직 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/Coordinator/MyPageCoordinator.swift
  RefillStation/RefillStation/Application/Coordinator/RegisterReviewCoordinator.swift
  RefillStation/RefillStation/Application/Coordinator/TabBarCoordinator.swift
  RefillStation/RefillStation/Application/DIContainer/MyPageDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/OnboardingDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/RegisterReviewDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/StoreDetailDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/TabBarDIContainer.swift
  RefillStation/RefillStation/Data/Repositories/MockRepositories.swift
  RefillStation/RefillStation/Domain/Entities/UserLevelInfo.swift
  RefillStation/RefillStation/Domain/UseCases/RegisterReview/RegisterReviewUseCase.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewPopUpViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewModel/DefaultTagReviewViewModel.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/UserLevelViewModel.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelHeaderView.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewController/UserLevelViewController.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
  RefillStation/RefillStation/Resources/images.xcassets/level_beginner.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/level_beginner.imageset/level_beginner.png
  RefillStation/RefillStation/Resources/images.xcassets/level_beginner.imageset/level_beginner@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/level_beginner.imageset/level_beginner@3x.png
  RefillStation/RefillStation/Resources/images.xcassets/level_fancier.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/level_fancier.imageset/level_fancier.png
  RefillStation/RefillStation/Resources/images.xcassets/level_fancier.imageset/level_fancier@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/level_fancier.imageset/level_fancier@3x.png
  RefillStation/RefillStation/Resources/images.xcassets/level_prospect.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/level_prospect.imageset/level_prospect.png
  RefillStation/RefillStation/Resources/images.xcassets/level_prospect.imageset/level_prospect@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/level_prospect.imageset/level_prospect@3x.png
  RefillStation/RefillStation/Resources/images.xcassets/level_regular.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/level_regular.imageset/level_regular.png
  RefillStation/RefillStation/Resources/images.xcassets/level_regular.imageset/level_regular@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/level_regular.imageset/level_regular@3x.png
Labels: ✨ feat, 💻 조지

#113 [Fix, Refactor] #112 랭크 잘못 표기되던 버그 수정 및 리팩토링
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: 🚨 bug, 🔧 refactor, 💻 조지

#110 [Feature/#109] Home, MyPage MockRepository를 통한 데이터 주입 및 화면 연결
  RefillStation/RefillStation/Application/Coordinator/MyPageCoordinator.swift
  RefillStation/RefillStation/Application/Coordinator/TabBarCoordinator.swift
  RefillStation/RefillStation/Application/DIContainer/MyPageDIContainer.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  RefillStation/RefillStation/Presentation/MyPageScene/MyPageViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/MyPageViewModel.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsDetailViewController.swift
Labels: ✨ feat, 💻 클로이

#115 Feature/#111
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/Coordinator/OnboardingCoordinator.swift
  RefillStation/RefillStation/Application/DIContainer/OnboardingDIContainer.swift
  RefillStation/RefillStation/Presentation/HomeScene/View/RegionRequestCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/HomeScene/View/RegionRequestHeaderView.swift
  RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewController.swift
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewController/RequestRegionViewController.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
  RefillStation/RefillStation/Resources/Info.plist
  RefillStation/RefillStation/Resources/images.xcassets/image_location info.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/image_location info.imageset/image_location info.png
  RefillStation/RefillStation/Resources/images.xcassets/image_location info.imageset/image_location info@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/image_location info.imageset/image_location info@3x.png
Labels: ✨ feat, 💻 클로이

#118 Feature/#117 테스트 플라이트 준비작업
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/AppDelegate.swift
  RefillStation/RefillStation/Application/Coordinator/OnboardingCoordinator.swift
  RefillStation/RefillStation/Data/Repositories/MockRepositories.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewController/LoginViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsPermissionViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/ReviewDescriptionCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewModel/DefaultTagReviewViewModel.swift
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/66.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/92.png
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: ✨ feat, 💻 조지

#122 Feature/#114 NetworkService 계층 제작, StoreRepo 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/DTOs/Store/ProductDTO.swift
  RefillStation/RefillStation/Data/DTOs/Store/ReviewDTO.swift
  RefillStation/RefillStation/Data/DTOs/Store/StoreDTO.swift
  RefillStation/RefillStation/Data/DTOs/Store/StoreRecommendDTO.swift
  RefillStation/RefillStation/Data/Repositories/RepositoryError.swift
  RefillStation/RefillStation/Data/Repositories/StoreRepository.swift
  RefillStation/RefillStation/Domain/UseCases/Store/FetchProductsUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/FetchStoreReviewsUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/FetchStoresUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/RecommendStoreUseCase.swift
  RefillStation/RefillStation/Infrastructure/Network/Exception.swift
  RefillStation/RefillStation/Infrastructure/Network/HTTPMethod.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkResult.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
Labels: ✨ feat, 💻 조지

#124 Feature/#121 추천수 가져오기 기능 제작, URLRequest 생성파트 리팩토링
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/DTOs/Store/FetchStoreRecommendDTO.swift
  RefillStation/RefillStation/Data/DTOs/Store/StoreDTO.swift
  RefillStation/RefillStation/Data/DTOs/Store/StoreRecommendDTO.swift
  RefillStation/RefillStation/Data/Repositories/MockRepositories.swift
  RefillStation/RefillStation/Data/Repositories/StoreRepository.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/StoreRepositoryInterface.swift
  RefillStation/RefillStation/Domain/UseCases/Store/FetchStoreRecommendUseCase.swift
  RefillStation/RefillStation/Infrastructure/URLComponentsExtension.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: ✨ feat, 💻 조지

#125 [Feature/#107] kakao Login API 연결
  .gitignore
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/AppDelegate.swift
  RefillStation/RefillStation/Application/Coordinator/OnboardingCoordinator.swift
  RefillStation/RefillStation/Application/DIContainer/OnboardingDIContainer.swift
  RefillStation/RefillStation/Data/DTOs/Account/LoginDTO.swift
  RefillStation/RefillStation/Data/DTOs/Account/SignUpDTO.swift
  RefillStation/RefillStation/Data/Repositories/AccountRepository.swift
  RefillStation/RefillStation/Data/Repositories/MockRepositories.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/AccountRepositoryInterface.swift
  RefillStation/RefillStation/Domain/UseCases/Account/OAuthLoginUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Account/SignUpUseCase.swift
  RefillStation/RefillStation/Info.plist
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewController/LoginViewController.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsPermissionViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsPermissionViewModel.swift
Labels: ✨ feat, 💻 클로이

#127 Feature/#123 이미지 업로드 로직 제작
  .gitignore
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Infrastructure/AWSS3Service.swift
Labels: ✨ feat, 💻 조지

#130 Feature/#129
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/DTOs/ReviewUploadDTO.swift
  RefillStation/RefillStation/Data/Repositories/RegisterReviewRepository.swift
  RefillStation/RefillStation/Data/Repositories/RepositoryError.swift
  RefillStation/RefillStation/Domain/UseCases/RegisterReview/RegisterReviewUseCase.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewModel/DefaultTagReviewViewModel.swift
Labels: ✨ feat, 💻 조지

#131 [Feature/#126] 애플로그인 구현
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/Repositories/AccountRepository.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewController/LoginViewController.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  RefillStation/RefillStation/RefillStation.entitlements
Labels: ✨ feat, 💻 클로이

#133 Feature/#128 UserInfoRepository 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Common/ImageUploadTask.swift
  RefillStation/RefillStation/Data/DTOs/Review/ReviewUploadDTO.swift
  RefillStation/RefillStation/Data/DTOs/User/EditUserRequestDTO.swift
  RefillStation/RefillStation/Data/DTOs/User/UserDTO.swift
  RefillStation/RefillStation/Data/Repositories/RegisterReviewRepository.swift
  RefillStation/RefillStation/Data/Repositories/UserInfoRepository.swift
  RefillStation/RefillStation/Domain/Entities/UserLevelInfo.swift
  RefillStation/RefillStation/Domain/UseCases/UserInfo/EditProfileUseCase.swift
  RefillStation/RefillStation/Infrastructure/AWSS3Service.swift
Labels: ✨ feat, 💻 조지

#136 Feature/#134 가게화면 QA 반영
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/MockEntityData.swift
  RefillStation/RefillStation/Presentation/Component/Extensions/UILabelExtension.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewTagCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/RankView.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfo/StoreDetailInfoViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/TabBar/StoreDetailTabBarCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailSection.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
  RefillStation/RefillStation/Resources/Fonts.swift
Labels: 🚨 bug, 🪄 style, 💻 조지

#137 [Feature/#132] 마이페이지 구현 완성
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/Coordinator/MyPageCoordinator.swift
  RefillStation/RefillStation/Application/DIContainer/MyPageDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/OnboardingDIContainer.swift
  RefillStation/RefillStation/Data/DTOs/User/EditUserRequestDTO.swift
  RefillStation/RefillStation/Data/DTOs/User/UserDTO.swift
  RefillStation/RefillStation/Data/Repositories/UserInfoRepository.swift
  RefillStation/RefillStation/Domain/Entities/User.swift
  RefillStation/RefillStation/Domain/Entities/UserLevelInfo.swift
  RefillStation/RefillStation/Domain/UseCases/UserInfo/EditProfileUseCase.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/AccountManagementViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewModel/AccountManagementViewModel.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewModel/NicknameViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsPermissionViewModel.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewController/UserLevelViewController.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewModel/UserLevelViewModel.swift
  RefillStation/RefillStation/Resources/TermsLiterals.swift
Labels: ✨ feat, 💻 클로이

#141 [QA/#140] 마이페이지 QA
  RefillStation/RefillStation/Application/AppDelegate.swift
  RefillStation/RefillStation/Application/Coordinator/TabBarCoordinator.swift
  RefillStation/RefillStation/Presentation/Component/PumpLargeTitleNavigationBar.swift
  RefillStation/RefillStation/Presentation/MainTabBarController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/AccountManagementViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewModel/NicknameViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsDetailViewController.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewController/UserLevelViewController.swift
Labels: 🚨 bug, 💻 클로이

#143 [QA/#139] 스플래시 추가, 온보딩, 로그인, 홈 QA 반영
  RefillStation/RefillStation/Application/DIContainer/TabBarDIContainer.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewController/LoginViewController.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsPermissionViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewController/RequestRegionViewController.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
  RefillStation/RefillStation/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  RefillStation/RefillStation/Resources/Base.lproj/LaunchScreen.storyboard
  RefillStation/RefillStation/Resources/images.xcassets/Icon_My.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/Icon_My.imageset/Icon_My.png
  RefillStation/RefillStation/Resources/images.xcassets/Icon_My.imageset/Icon_My@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/Icon_My.imageset/Icon_My@3x.png
  RefillStation/RefillStation/Resources/images.xcassets/Icon_Search.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/Icon_Search.imageset/Icon_Search.png
  RefillStation/RefillStation/Resources/images.xcassets/Icon_Search.imageset/Icon_Search@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/Icon_Search.imageset/Icon_Search@3x.png
  RefillStation/RefillStation/Resources/images.xcassets/Icon_pump.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/Icon_pump.imageset/Icon_pump.png
  RefillStation/RefillStation/Resources/images.xcassets/Icon_pump.imageset/Icon_pump@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/Icon_pump.imageset/Icon_pump@3x.png
  RefillStation/RefillStation/Resources/images.xcassets/loginbackground.imageset/loginbackground.png
  RefillStation/RefillStation/Resources/images.xcassets/loginbackground.imageset/loginbackground@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/loginbackground.imageset/loginbackground@3x.png
Labels: 🚨 bug, 💻 클로이, 🧹 chore

#142 Feature/#135 CS, Account 레포 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/DIContainer/MyPageDIContainer.swift
  RefillStation/RefillStation/Data/DTOs/Account/RandomNicknameDTO.swift
  RefillStation/RefillStation/Data/DTOs/Account/WithdrawDTO.swift
  RefillStation/RefillStation/Data/DTOs/CustomerSatisfaction/CustomerSatisfactionDTO.swift
  RefillStation/RefillStation/Data/KeychainManager.swift
  RefillStation/RefillStation/Data/Repositories/AccountRepository.swift
  RefillStation/RefillStation/Data/Repositories/CustomerSatisfactionRepository.swift
  RefillStation/RefillStation/Data/Repositories/MockRepositories.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/AccountRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/CustomerSatisfactionRepositoryInterface.swift
  RefillStation/RefillStation/Domain/UseCases/Account/SignOutUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/CustomerSatisfaction/CustomerSatisfactionUseCase.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewModel/AccountManagementViewModel.swift
Labels: ✨ feat, 💻 조지

#146 Refactor/#144 서버통신 로직 async await로 리팩토링
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/DIContainer/MyPageDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/OnboardingDIContainer.swift
  RefillStation/RefillStation/Data/DTOs/Store/ReviewDTO.swift
  RefillStation/RefillStation/Data/Repositories/AsyncAccountRepository.swift
  RefillStation/RefillStation/Data/Repositories/AsyncCustomerSatisfactionRepository.swift
  RefillStation/RefillStation/Data/Repositories/AsyncRegisterReviewRepository.swift
  RefillStation/RefillStation/Data/Repositories/AsyncStoreRepository.swift
  RefillStation/RefillStation/Data/Repositories/AsyncUserInfoRepository.swift
  RefillStation/RefillStation/Data/Repositories/Deprecated/AccountRepository.swift
  RefillStation/RefillStation/Data/Repositories/Deprecated/CustomerSatisfactionRepository.swift
  RefillStation/RefillStation/Data/Repositories/Deprecated/RegisterReviewRepository.swift
  RefillStation/RefillStation/Data/Repositories/Deprecated/StoreRepository.swift
  RefillStation/RefillStation/Data/Repositories/Deprecated/UserInfoRepository.swift
  RefillStation/RefillStation/Data/Repositories/MockRepositories.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/AsyncAccountRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/AsyncCustomerSatisfactionRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/AsyncRegisterReviewRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/AsyncStoreRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/AsyncUserInfoRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/RegisterReviewRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/UploadImageRepositoryInterface.swift
  RefillStation/RefillStation/Domain/UseCases/Account/CreateNicknameUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Account/OAuthLoginUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Account/SignOutUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Account/SignUpUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Account/WithdrawUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Common/UploadImageUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/CustomerSatisfaction/CustomerSatisfactionUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/RegisterReview/RegisterReviewUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/FetchProductsUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/FetchStoreRecommendUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/FetchStoreReviewsUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/FetchStoresUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Store/RecommendStoreUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/UserInfo/EditProfileUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/UserInfo/FetchUserInfoUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/UserInfo/FetchUserReviewsUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/UserInfo/ValidNicknameUseCase.swift
  RefillStation/RefillStation/Infrastructure/AWSS3Service.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewModel/AccountManagementViewModel.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewModel/NicknameViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewModel.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewModel/DefaultTagReviewViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailSection.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewController/UserLevelViewController.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewModel/UserLevelViewModel.swift
Labels: 🔧 refactor, 💻 조지

#151 [Feature/#149] 로그인시 User의 Type 추가, email과 name 옵셔널로 변경, 로그아웃/탈퇴시 로그인 뷰로 보내는 로직 추가
  RefillStation/RefillStation/Data/DTOs/Account/LoginDTO.swift
  RefillStation/RefillStation/Data/DTOs/Account/SignUpDTO.swift
  RefillStation/RefillStation/Domain/UseCases/Account/OAuthLoginUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Account/SignUpUseCase.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewController/LoginViewController.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewModel/AccountManagementViewModel.swift
Labels: 🚨 bug, 💻 클로이, 🧹 chore

#150 Feature/#148 이미지 다운로드 기능 연결
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/Coordinator/HomeCoordinator.swift
  RefillStation/RefillStation/Application/Coordinator/MyPageCoordinator.swift
  RefillStation/RefillStation/Application/Coordinator/StoreDetailCoordinator.swift
  RefillStation/RefillStation/Application/DIContainer/HomeDIContainer.swift
  RefillStation/RefillStation/Common/Cancellable.swift
  RefillStation/RefillStation/Data/DTOs/Store/ReviewDTO.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
  RefillStation/RefillStation/Presentation/Component/Extensions/NSAttributedStringExtension.swift
  RefillStation/RefillStation/Presentation/Component/Extensions/UILabelExtension.swift
  RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/AccountManagementViewController.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/Section.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/ReviewPhotosCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewPopUpViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewModel/DefaultTagReviewViewModel.swift
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewController/RequestRegionViewController.swift
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewModel/RequestRegionViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/OperationInfo/OperationInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/FilteredProductCountCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCategoriesCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailPhotoReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailPhotoReviewViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewReportPopUpViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailSection.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
  RefillStation/RefillStation/Resources/Assets+Generated.swift
  RefillStation/RefillStation/Resources/Fonts.swift
  RefillStation/RefillStation/Resources/images.xcassets/store defualt image.imageset/Contents.json
  RefillStation/RefillStation/Resources/images.xcassets/store defualt image.imageset/store defualt image.png
  RefillStation/RefillStation/Resources/images.xcassets/store defualt image.imageset/store defualt image@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/store defualt image.imageset/store defualt image@3x.png
Labels: 🔧 refactor, ✨ feat, 💻 조지

#154 Qa/#153 1.0(2) QA 반영
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Domain/Entities/UserLevelInfo.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
  RefillStation/RefillStation/Presentation/Component/Extensions/UIViewControllerExtension.swift
  RefillStation/RefillStation/Presentation/Component/PumpPopUpViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewController/LoginViewController.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/AccountManagementViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewModel/AccountManagementViewModel.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewModel/MyPageViewModel.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewModel/NicknameViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsPermissionViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewModel/DefaultTagReviewViewModel.swift
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewController/RequestRegionViewController.swift
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewModel/RequestRegionViewModel.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/OperationInfo/OperationInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailPhotoReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfo/StoreDetailInfoViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailSection.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelHeaderView.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewController/UserLevelViewController.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewModel/UserLevelViewModel.swift
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding2.imageset/img_onboarding2.png
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding2.imageset/img_onboarding2@2x.png
  RefillStation/RefillStation/Resources/images.xcassets/img_onboarding2.imageset/img_onboarding2@3x.png
Labels: 💻 조지

#157 [Feature/#152] 리뷰 등록, 회원등급, 마이페이지, 위치권한 QA 반영
  RefillStation/RefillStation/Data/DTOs/Account/LoginDTO.swift
  RefillStation/RefillStation/Data/DTOs/Account/SignUpDTO.swift
  RefillStation/RefillStation/Data/Repositories/AsyncUserInfoRepository.swift
  RefillStation/RefillStation/Domain/UseCases/Account/OAuthLoginUseCase.swift
  RefillStation/RefillStation/Domain/UseCases/Account/SignUpUseCase.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/ReviewDescriptionCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewPopUpViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelHeaderView.swift
Labels: 🚨 bug, 💻 클로이, 🧹 chore

#158 [Feature/#145] HomeVC 스켈레톤 적용
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
Labels: 🪄 style, 💻 클로이, 🧹 chore

#160 [Qa/#159] 자잘한 QA, 위치권한 로직 수정
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewController/LoginViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsDetailViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsPermissionViewController.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelHeaderView.swift
Labels: 🚨 bug, 💻 클로이

#162 Qa/#161 1.0(3) QA 반영
  RefillStation/RefillStation/Presentation/Component/PumpPopUpViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/OperationInfo/OperationInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailPhotoReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
Labels: 🚨 bug, 💻 조지

#168 [Qa/#167] 1.0(8) QA 대응 / 지역신청 텍스트뷰 레이아웃 수정
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewController/RequestRegionViewController.swift
Labels: 🚨 bug, 💻 클로이

#170 Qa/#169 1.0(9) 대응
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/ReviewPhotosCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
Labels: 🚨 bug, 🔧 refactor, 💻 조지

#172 Qa/#171 1.0(10) 대응
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailPhotoReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailSection.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
Labels: 🚨 bug, 💻 조지

#176 [Feat] #175 카카오 계정으로 로그인 추가
  RefillStation/RefillStation/Presentation/LoginScene/ViewModel/LoginViewModel.swift
Labels: ✨ feat, 💻 클로이

#182 Qa/#181 메모리 릭 해결
  RefillStation/RefillStation/Application/AppDelegate.swift
  RefillStation/RefillStation/Application/Coordinator/MyPageCoordinator.swift
  RefillStation/RefillStation/Application/Coordinator/StoreDetailCoordinator.swift
  RefillStation/RefillStation/Application/DIContainer/HomeDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/MyPageDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/RegisterReviewDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/StoreDetailDIContainer.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewController/LoginViewController.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/AccountManagementViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  RefillStation/RefillStation/Presentation/NicknameScene/ViewController/NicknameViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsPermissionViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewController/RequestRegionViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailPhotoReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewReportPopUpViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewController/UserLevelViewController.swift
Labels: 🚨 bug, 💻 조지

#185 Feature/#183 변경된 로그인 플로우 적용
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/AppDelegate.swift
  RefillStation/RefillStation/Application/Coordinator/Coordinator.swift
  RefillStation/RefillStation/Application/Coordinator/MyPageCoordinator.swift
  RefillStation/RefillStation/Application/Coordinator/OnboardingCoordinator.swift
  RefillStation/RefillStation/Application/Coordinator/TabBarCoordinator.swift
  RefillStation/RefillStation/Application/DIContainer/MyPageDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/OnboardingDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/StoreDetailDIContainer.swift
  RefillStation/RefillStation/Application/DIContainer/TabBarDIContainer.swift
  RefillStation/RefillStation/Data/KeychainManager.swift
  RefillStation/RefillStation/Data/Repositories/AsyncAccountRepository.swift
  RefillStation/RefillStation/Domain/UseCases/Account/OAuthLoginUseCase.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewController/LoginViewController.swift
  RefillStation/RefillStation/Presentation/LoginScene/ViewModel/LoginViewModel.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/AccountManagementViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/LocationPermissionViewModel.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsPermissionViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
Labels: ✨ feat, 💻 조지

#190 Qa/#187 사진 업로드 에러 해결
  RefillStation/RefillStation/Data/Repositories/AsyncRegisterReviewRepository.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailPhotoReviewViewController.swift
Labels: 🚨 bug, 💻 조지

#191 Qa/#188 백그라운드 버그 수정
  RefillStation/RefillStation/Presentation/HomeScene/View/RegionRequestCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/HomeScene/View/StoreCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/OnboardingViewController.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/ReviewDescriptionCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/ReviewPhotosCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/StoreInfoCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/TagReviewCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/VoteTitleCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/OperationInfo/OperationInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/OperationInfo/OperationNoticeCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/FilteredProductCountCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCategoriesCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCategoryCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/ProductList/ProductCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/DetailReviewTagCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/Review/ReviewInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfo/StoreDetailInfoViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/TabBar/StoreDetailTabBarCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/View/LevelCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewController/UserLevelViewController.swift
Labels: 🚨 bug, 💻 조지

#193 [Feature/#192] 지역 신청시 헤더 숨기기
  RefillStation/RefillStation/Data/Repositories/AsyncAccountRepository.swift
  RefillStation/RefillStation/Data/Repositories/AsyncCustomerSatisfactionRepository.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
  RefillStation/RefillStation/Presentation/RequestRegionScene/ViewController/RequestRegionViewController.swift
Labels: ✨ feat, 💻 클로이

#195 Feature/#194 방문가이드 화면 제작
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/Coordinator/StoreDetailCoordinator.swift
  RefillStation/RefillStation/Application/DIContainer/StoreDetailDIContainer.swift
  RefillStation/RefillStation/Data/DTOs/Store/StoreDTO.swift
  RefillStation/RefillStation/Data/MockEntityData.swift
  RefillStation/RefillStation/Domain/Entities/Store.swift
  RefillStation/RefillStation/Presentation/HomeScene/View/RegionRequestCollectionViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfo/StoreDetailInfoViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/RefillGuideViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailSection.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/RefillGuideViewModel.swift
Labels: ✨ feat, 💻 조지

#197 [Feat] #196 방문가이드 화면에 스켈레톤 뷰 추가
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/RefillGuideViewController.swift
Labels: ✨ feat, 💻 조지

#201 Qa/#200
  RefillStation/RefillStation/Data/Repositories/AsyncAccountRepository.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewModel/HomeViewModel.swift
Labels: 🚨 bug, 💻 조지

#203 Qa/#202 iOS 직군 QA 반영
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/OperationInfo/OperationInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/StoreDetailInfo/StoreDetailInfoViewCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: ✨ feat, 💻 조지

#205 Qa/#204 로그인 유도화면 이전에 얼럿 띄우기 및 UX 개선작업
  RefillStation/RefillStation/Application/Coordinator/HomeCoordinator.swift
  RefillStation/RefillStation/Presentation/Component/Extensions/UIViewControllerExtension.swift
  RefillStation/RefillStation/Presentation/Component/PumpPopUpViewController.swift
  RefillStation/RefillStation/Presentation/HomeScene/ViewController/HomeViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/AccountManagementViewController.swift
  RefillStation/RefillStation/Presentation/MyPageScene/ViewController/MyPageViewController.swift
  RefillStation/RefillStation/Presentation/OnboardingScene/TermsDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/UserLevelScene/ViewController/UserLevelViewController.swift
Labels: 🔧 refactor, ✨ feat, 💻 조지

#207 Qa/#206
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Application/AppDelegate.swift
  RefillStation/RefillStation/Data/KeychainManager.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/Section.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/View/StoreInfoCell.swift
  RefillStation/RefillStation/Presentation/RegisterReviewScene/ViewController/RegisterReviewViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/View/OperationInfo/OperationInfoCell.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewController/StoreDetailViewController.swift
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
Labels: 🔧 refactor, ✨ feat, 💻 조지

#209 [Chore] #208 주소 구분자 제거
  RefillStation/RefillStation/Data/DTOs/Store/StoreDTO.swift
Labels: 💻 클로이, 🧹 chore

#210 Test/#179 레포지토리 테스트
  RefillStation/.swiftlint.yml
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/MockEntityData.swift
  RefillStation/RefillStation/Data/Repositories/AsyncCustomerSatisfactionRepository.swift
  RefillStation/RefillStation/Data/Repositories/AsyncRegisterReviewRepository.swift
  RefillStation/RefillStation/Data/Repositories/AsyncUserInfoRepository.swift
  RefillStation/RefillStation/Data/Repositories/Deprecated/AccountRepository.swift
  RefillStation/RefillStation/Data/Repositories/Deprecated/CustomerSatisfactionRepository.swift
  RefillStation/RefillStation/Data/Repositories/Deprecated/RegisterReviewRepository.swift
  RefillStation/RefillStation/Data/Repositories/Deprecated/StoreRepository.swift
  RefillStation/RefillStation/Data/Repositories/Deprecated/UserInfoRepository.swift
  RefillStation/RefillStation/Data/Repositories/MockRepositories.swift
  RefillStation/RefillStation/Infrastructure/AWSS3Service.swift
  RefillStation/RefillStation/Infrastructure/Network/NetworkService.swift
  RefillStation/RefillStationTests/RefillStationTests.swift
  RefillStation/RefillStationTests/RepositoryTests/Account/OAuthLoginTest.swift
  RefillStation/RefillStationTests/RepositoryTests/CustomerSatisfaction/CustomerSatisfactionUploadTest.swift
  RefillStation/RefillStationTests/RepositoryTests/CustomerSatisfaction/MockUserInfoRepository.swift
  RefillStation/RefillStationTests/RepositoryTests/MockAWSS3Service.swift
  RefillStation/RefillStationTests/RepositoryTests/MockNetworkService.swift
  RefillStation/RefillStationTests/RepositoryTests/RegisterReview/RegisterReviewTest.swift
  RefillStation/RefillStationTests/RepositoryTests/Store/FetchProductsTest.swift
  RefillStation/RefillStationTests/RepositoryTests/Store/FetchStoreRecommendTest.swift
  RefillStation/RefillStationTests/RepositoryTests/Store/FetchStoreReviewsTest.swift
  RefillStation/RefillStationTests/RepositoryTests/Store/FetchStoresTest.swift
  RefillStation/RefillStationTests/RepositoryTests/Store/RecommendStoreTest.swift
Labels: 💻 조지, ✅ test

#213 Test/#212 DTO Tests
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/DTOs/User/UserDTO.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/AccountRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/CustomerSatisfactionRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/RegisterReviewRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/StoreRepositoryInterface.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/UserInfoRepositoryInterface.swift
  RefillStation/RefillStationTests/DTOTests/Account/LoginDTOTests.swift
  RefillStation/RefillStationTests/DTOTests/Store/FetchStoreRecommendDTOTests.swift
  RefillStation/RefillStationTests/DTOTests/Store/ProductDTOTests.swift
  RefillStation/RefillStationTests/DTOTests/Store/ReviewDTOTests.swift
  RefillStation/RefillStationTests/DTOTests/Store/StoreDTOTests.swift
  RefillStation/RefillStationTests/DTOTests/Store/StoreRecommendDTOTests.swift
  RefillStation/RefillStationTests/DTOTests/User/UserDTOTests.swift
  RefillStation/RefillStationUITests/RefillStationUITests.swift
  RefillStation/RefillStationUITests/RefillStationUITestsLaunchTests.swift
Labels: 💻 조지, ✅ test

#214 [Test/#211] Account, UserInfo Repository 테스트
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Data/KeychainManager.swift
  RefillStation/RefillStation/Data/Repositories/AsyncAccountRepository.swift
  RefillStation/RefillStation/Domain/Interfaces/Repositories/AsyncAccountRepositoryInterface.swift
  RefillStation/RefillStation/Domain/UseCases/Account/CreateNicknameUseCase.swift
  RefillStation/RefillStationTests/RepositoryTests/Account/SignOutTest.swift
  RefillStation/RefillStationTests/RepositoryTests/Account/SignUpTest.swift
  RefillStation/RefillStationTests/RepositoryTests/Account/WithdrawTest.swift
  RefillStation/RefillStationTests/RepositoryTests/RegisterReview/MockKeychainManager.swift
  RefillStation/RefillStationTests/RepositoryTests/UserInfo/EditProfileTest.swift
  RefillStation/RefillStationTests/RepositoryTests/UserInfo/FetchProfileTest.swift
  RefillStation/RefillStationTests/RepositoryTests/UserInfo/FetchUserReviewsTest.swift
  RefillStation/RefillStationTests/RepositoryTests/UserInfo/ValidNicknameTest.swift
Labels: 💻 클로이, ✅ test

#216 Test/#215 StoreDetailViewModel 테스트
  RefillStation/RefillStation.xcodeproj/project.pbxproj
  RefillStation/RefillStation/Presentation/StoreDetailScene/ViewModel/StoreDetailViewModel.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/Account/MockOAuthLoginUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/Account/MockSignOutUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/Account/MockSignUpUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/Account/MockWithdrawUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/CustomerSatisfaction/MockCustomerSatisfactionUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/RegisterReview/MockRegisterReviewUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/Store/MockFetchProductsUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/Store/MockFetchStoreRecommendUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/Store/MockFetchStoreReviewsUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/Store/MockFetchStoresUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/Store/MockRecommendStoreUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/UserInfo/MockEditProfileUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/UserInfo/MockFetchUserInfoUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/UserInfo/MockFetchUserReviewsUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/MockUseCases/UserInfo/MockValidNicknameUseCase.swift
  RefillStation/RefillStationTests/ViewModelTests/StoreDetail/OperationInfoTests.swift
  RefillStation/RefillStationTests/ViewModelTests/StoreDetail/ProductsTests.swift
  RefillStation/RefillStationTests/ViewModelTests/StoreDetail/ReviewsTests.swift
  RefillStation/RefillStationTests/ViewModelTests/StoreDetail/StoreInfo+TabbarTests.swift
Labels: 💻 조지, ✅ test
